package p0;

public class Mirar {

	// TE MIRO Y VUELVO A MIRAR.
	
	
	
	// ... AHORA OTRO CAMBIO PARA PROBAR EL PUSH SIN NECESIDAD DE USAR LA PANTALLA GIT STAGING
	// CUANDO HAY CAMBIO, APARECE UN SIGNO > A LA IZQUIERDA DEL FICHERO MODIFICADO.
	
	int x = 8;
}
